//
// Created by kevin on 2022/11/3.
//

#ifndef HTTPSERVER_AP_RELEASE_H
#define HTTPSERVER_AP_RELEASE_H

#define AP_SERVER_BASEPRODUCT "Apache"

/* use a group of macros to define ap_server_version, just some number, could be changed. */
#define AP_SERVER_MAJORVERSION_NUMBER  2
#define AP_SERVER_MINORVERSION_NUMBER  5
#define AP_SERVER_PATCHLEVEL_NUMBER    1
#define AP_SERVER_DEVBUILD_BOOLEAN     1

#if !AP_SERVER_DEVBUILD_BOOLEAN
#define AP_SERVER_ADD_STRING  ""
#else
#ifndef AP_SERVER_ADD_STRING
#define AP_SERVER_ADD_STRING   "-dev"
#endif
#endif

#ifndef APR_STRINGIFY
/** properly quota a value as string in c compiler preprocess */
#define APR_STRINGIFY(n) APR_STRINGIFY_HELPER(n)
/** helper macro for APR_STRINGIFY */
#define APR_STRINGIFY_HELPER(n)  #n
#endif

#define AP_SERVER_MAJORVERSION  APR_STRINGIFY(AP_SERVER_MAJORVERSION_NUMBER)
#define AP_SERVER_MINORVERSION  APR_STRINGIFY(AP_SERVER_MINORVERSION_NUMBER)
#define AP_SERVER_PATCHLEVEL    APR_STRINGIFY(AP_SERVER_PATCHLEVEL_NUMBER) AP_SERVER_ADD_STRING


#define AP_SERVER_MINORREVISION AP_SERVER_MAJORVERSION "." AP_SERVER_MINORVERSION
#define AP_SERVER_BASEREVISION  AP_SERVER_MINORREVISION "." AP_SERVER_PATCHLEVEL
#define AP_SERVER_BASEVERSION   AP_SERVER_BASEPRODUCT "/" AP_SERVER_BASEREVISION


#endif //HTTPSERVER_AP_RELEASE_H
